### ISSUE TITLE
When i run a single case,there is a problem connecting to the database

### ISSUE THREAD

**Issue by jsforyu** [seclab-ucr/LLift#1]
error:psycopg2.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
I found the code written like this
`DB_CONFIG = 'postgresql://ubiuser1:ubitect@db:5432/ubidb1'`
I modified the code to look like this
`DB_CONFIG = 'postgresql://ubiuser1:ubitect@localhost:5432/ubidb1'`
error still exists,how i resolve it

**Comment by Tert-butyllithium** [comment]
Are you building with the docker? the "db" should refer to the container "db" if you create it correctly

**Comment by jsforyu** [comment]
> Are you building with the docker? the "db" should refer to the container "db" if you create it correctly

oh ,running a single case also needs docker.Thank you!By the way ,can you give me a command-line example of running a single program ？૮(˶ᵔ ᵕ ᵔ˶)ა
